services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    expose:
      - "3000"
  caddy:
    image: caddy:2
    restart: always
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web
volumes:
  caddy_data:
  caddy_config:
